from enum import Enum

class LeverState(Enum):
    STOPPED = "STOPPED"
    MOVING_UP = "MOVING_UP"
    MOVING_DOWN = "MOVING_DOWN"
    SLOWING_UP = "SLOWING_UP"
    SLOWING_DOWN = "SLOWING_DOWN"
    STARTING_UP = "STARTING_UP"
    STARTING_DOWN = "STARTING_DOWN"
    SEALING = "SEALING"
    PAUSED = "PAUSED"
    AT_TOP = "AT_TOP"
    AT_BOTTOM = "AT_BOTTOM"
    ERROR = "ERROR"

class LeverEvent(Enum):
    PULL_UP = "PULL_UP"
    PULL_DOWN = "PULL_DOWN"
    PAUSE = "PAUSE"
    RESUME = "RESUME"
    STOP = "STOP"
    TICK = "TICK"
    REACHED_TOP = "REACHED_TOP"
    REACHED_BOTTOM = "REACHED_BOTTOM"
    SEAL_CONDITIONS_MET = "SEAL_CONDITIONS_MET"
    SEAL_COMPLETE = "SEAL_COMPLETE"
    REVERSED = "REVERSED"
    ERROR_OCCURRED = "ERROR_OCCURRED"

class TransitionResult(Enum):
    SUCCESS = "SUCCESS"
    IGNORED = "IGNORED"
    INVALID = "INVALID"
    BLOCKED = "BLOCKED"